# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }

  backend "s3" {
    bucket       = "mbg-terraform-state"
    use_lockfile = true
    key          = "accounts/mbg-security/terraform.tfstate"
    region       = "us-west-2"
    encrypt      = true
  }
}

provider "aws" {
  region = "us-west-2"

  assume_role {
    role_arn     = "arn:aws:iam::777777777777:role/TerraformAdminRole"
    session_name = "terraform-session"
  }
}
