name: Lint and Test Setup Scripts

on: 
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  lint-and-test-setup-scripts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./setup-scripts
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Python Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/uv
            ~/.cache/hatch
          key: ${{ runner.os }}-setup-scripts-${{ matrix.python-version }}-${{ hashFiles('setup-scripts/requirements.lock', 'setup-scripts/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-setup-scripts-${{ matrix.python-version }}-

      - name: Setup Hatch and UV
        run: |
          pip install hatch uv
      
      - name: Create Hatch Environment
        run: hatch env create env
        
      - name: Install Setup Scripts Dependencies
        run: hatch run env:install-script-deps
      
      - name: Lint Setup Scripts
        run: hatch run env:lint-scripts
      
      - name: Test Setup Scripts
        run: hatch run env:test-scripts
